# Generated by Django 2.2.2 on 2019-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('skills', models.CharField(blank=True, max_length=1000)),
                ('projectexplained', models.CharField(blank=True, max_length=2000)),
                ('cost', models.IntegerField()),
                ('fori', models.BooleanField()),
                ('barjaste', models.BooleanField()),
                ('motamayez', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=200)),
                ('lname', models.CharField(blank=True, max_length=200)),
                ('emailAdd', models.EmailField(blank=True, max_length=254)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.IntegerField(default=1)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
