# Generated by Django 2.2.2 on 2019-06-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kariz', '0002_auto_20190617_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=200)),
                ('lname', models.CharField(blank=True, max_length=200)),
                ('emailAdd', models.EmailField(blank=True, max_length=254)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('phoneNum', models.IntegerField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('skills', models.CharField(blank=True, max_length=1000)),
                ('projectexplained', models.CharField(blank=True, max_length=2000)),
                ('cost', models.IntegerField()),
                ('fori', models.BooleanField()),
                ('motamayez', models.BooleanField()),
                ('creatoruname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kariz.User')),
            ],
        ),
    ]
