# Generated by Django 2.2.2 on 2019-06-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0003_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creatoruname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kariz.User'),
        ),
    ]
