# Generated by Django 2.2.2 on 2019-06-19 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0004_auto_20190617_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creatoruname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
