# Generated by Django 2.2.2 on 2019-07-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Kariz', '0006_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
