# Generated by Django 2.2.2 on 2019-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0007_delete_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('projects', models.ManyToManyField(blank=True, null=True, to='Kariz.Project')),
            ],
        ),
    ]
