# Generated by Django 2.2.2 on 2019-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0008_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='projects',
            field=models.ManyToManyField(blank=True, default='Null', null=True, to='Kariz.Project'),
        ),
    ]
