# Generated by Django 2.2.2 on 2019-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0009_auto_20190708_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='Kariz.Project'),
        ),
    ]
