# Generated by Django 2.2.2 on 2019-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0010_auto_20190708_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
