# Generated by Django 2.2.2 on 2019-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0011_auto_20190708_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('numberOfAllProjects', models.IntegerField(default=0)),
                ('numberOfDoneProjects', models.IntegerField(default=0)),
                ('sore', models.IntegerField(default=0)),
                ('currentProjects', models.ManyToManyField(blank=True, null=True, to='Kariz.Project')),
            ],
        ),
    ]
