# Generated by Django 2.2.2 on 2019-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0013_freelancer_teachingpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachingform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=150)),
                ('ability', models.CharField(blank=True, max_length=500)),
                ('resume', models.CharField(blank=True, max_length=2000)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
