# Generated by Django 2.2.2 on 2019-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0014_teachingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
