# Generated by Django 2.2.2 on 2019-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kariz', '0015_employer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('skill', models.CharField(blank=True, max_length=1000)),
                ('numberOfAllProjects', models.IntegerField(default=0)),
                ('sore', models.IntegerField(default=0)),
                ('numberOfDoneProjects', models.IntegerField(default=0)),
                ('currentProjects', models.ManyToManyField(blank=True, null=True, to='Kariz.Project')),
            ],
        ),
    ]
